import type { Metadata } from "next";
import "./globals.css";

import Hero from "@/components/Hero";
import Footer from "@/components/Footer"

export const metadata: Metadata = {
  title: "Anime now",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`max-w-7xl mx-auto bg-[#0F1110]`}
      >
        <Hero />
        {children}
        <Footer />
      </body>
    </html>
  );
}
